# Generated by Django 6.0.6 on 2026-06-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_siteconfig_provider_model_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='auto_generate_keywords',
            field=models.BooleanField(default=True),
        ),
    ]
